name: first-workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: PrintGreeting
        run: echo "HI-BYE"
  second-job:
    runs-on: ubuntu-latest
    steps: 
      - name: got it
        run: echo "GOT IT"
